---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-leader-claim
  namespace: ci
  labels:
    app: jenkins-leader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: general

